---

# Requests library is required for the github status script.
- name: Install requests Python library
  pip: name=requests state=present
# tox is needed for running codejail tests
- name: Install requests Python library
  pip: name=tox state=present
  when: codejail_worker is defined

# Versions of Python newer than 3.5 are not available in the default
# package index for Ubuntu 16.04. Add the deadsnakes PPA for anything
# newer
- name: add deadsnakes PPA for newer Python versions
  apt_repository:
    repo: "ppa:fkrull/deadsnakes"
    update_cache: yes
  when: ansible_distribution_release == 'xenial'

# Install newer versions of python for testing, but do not set them
# as the default version
- name: Install python versions
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items: '{{ python_versions }}'

# Install newer versions of python for testing, but do not set them
# as the default version
- name: Install python development packages
  apt:
    name: '{{ item }}-dev'
    state: present
    update_cache: yes
  with_items: '{{ python_versions }}'
