---

# Stateless app server configuration, designed to be used with external mysql,
# mongo, rabbitmq, and elasticsearch services.

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True

  vars:
    migrate_db: 'yes'
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    NGINX_SET_X_FORWARDED_HEADERS: True
    ENABLE_ECOMMERCE: False  # Disable ecommerce by default
  roles:

    # Ensure we have no known security vulnerabilities
    - security

    # Server setup
    - swapfile

    # Nginx reverse proxy
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
      
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    # Main EdX application
    # https://github.com/edx/edx-platform
    - role: edxapp
      celery_worker: True
    - edxapp
    
    - oauth_client_setup
    - oraclejdk
    - role: elasticsearch
      when: "'localhost' in EDXAPP_ELASTIC_SEARCH_CONFIG|map(attribute='host')"

    # Discussion forums
    # https://github.com/edx/cs_comments_service
    - forum

    # Notifications service
    # https://github.com/edx/notifier
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: '5'

    # XQueue interface for communicating with external grader services
    # https://github.com/edx/xqueue
    - role: xqueue
      update_users: True

    # Certificate generation
    # https://github.com/edx/edx-certificates
    - certs

    # Email sending
    - postfix_queue
       
    # memcached
    - role: memcache

    # Ecommerce (optional)
    # https://github.com/edx/ecommerce
    - role: nginx
      nginx_sites:
      - ecommerce
      when: ENABLE_ECOMMERCE
    - role: ecommerce
      when: ENABLE_ECOMMERCE
    - role: ecomworker
      when: ENABLE_ECOMMERCE

    # Optional extras
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
